basic api methods
TonyShad/APIServer pull request #1
Opened 2017-05-09 18:30 UTC by TonyShad

2017-05-10 14:33 UTC, mcsim4s requested changes

2017-05-10 14:33 UTC, mcsim4s commented on app/controllers/user/index.js
> +    console.log(this.req.body);
Все "console.log" только при отладке. Если в проде реально нужно что-то залогировать - используй либы для логирования

2017-05-10 14:33 UTC, mcsim4s commented on app/controllers/user/index.js
> +        return "Saved to DB";
Возвращаешь значение до того, как юзер будет реально сохранен в базу.
Либо весь метод нужно обернуть в промисс, либо(что мне кажется лучше) метод user.save должен возвращать промисс сам. 

Т.е. сдесь будет просто return user.save().

2017-05-10 14:33 UTC, mcsim4s commented on app/controllers/user/index.js
> +    try {
Не надо юзать try/catch внутри action. Каждый action и так обернут в промисс, если возникнет исключение, оно будет перехвачено в роутере [тут](https://github.com/TonyShad/APIServer/blob/master/app/middleware/router.js#L11)

2017-05-10 14:33 UTC, mcsim4s commented on app/controllers/user/index.js
> +UserController.registerAction('login', function(){
У тебя вот этот action вообще не возвращает значения. return ты делаешь только в коллбеке, а return коллбека никто не обрабатывает.
Нужно, чтобы action возвращал либо непосредственно значение, которое улетит в ответ, либо промисс, который вернет значение.
Соответсвенно  в этом методе скорее всего должно быть что то типа 
return User.findOne(filter)
    .then((user) => {
        return user.auth(password);
     })
    .then((authResult) => {
         ok/ не ok;
         setCookie;
         return {headers: { name: 'cookie', val: cookie }};
     );

2017-05-10 14:33 UTC, mcsim4s commented on app/controllers/user/index.js
> +UserController.registerAction('logout', function(){
Не возвращаешь ни значение ни ошибку

2017-05-10 14:33 UTC, mcsim4s commented on app/controllers/user/index.js
> +UserController.registerAction('getDecks', function(){
Не возвращаешь ни значение ни ошибку

2017-05-10 14:33 UTC, mcsim4s commented on app/controllers/user/index.js
> +                return model;
return только в коллбеке, который никто не обрабатывает

2017-05-10 14:46 UTC, mcsim4s requested changes

2017-05-10 14:46 UTC, McSim1993 commented on app/controllers/user/index.js
> +                    return({header: cookie});
Насчет кук. Нужно либо все ответы action-ов привести к одному виду, типа 
{
  response,
  headers
}, и в роутере его разбирать. Либо можно в конструктор контроллера передовать объект res, и если нужно поставить куки, то делать this.res.cookie(cookieVal);
А вообще у нас тут api. Api, строго говоря, не должно работать с cookie.

2017-05-11 08:26 UTC, TonyShad commented on app/controllers/user/index.js
> +                    return({header: cookie});
@McSim1993 Тогда, когда юзер логинится, как мне определять, что он залогинен при его следующем запросе на user/decks, например?

2017-05-12 09:13 UTC, mcsim4s requested changes

2017-05-12 09:13 UTC, McSim1993 commented on app/controllers/user/index.js
> +            this.res.writeHead("Saved to DB");
что такое writeHead?

2017-05-12 09:13 UTC, McSim1993 commented on app/controllers/user/index.js
>  	const user = new User(this.req.body);
Что случится, если req.body содержит невалидные данные

2017-05-12 09:13 UTC, McSim1993 commented on app/controllers/user/index.js
> +    console.log(session);
console.log ...

2017-05-12 09:13 UTC, McSim1993 commented on app/controllers/user/index.js
> +                session.save(function(err) {
Session.save - это асинхронная операция?

2017-05-12 09:13 UTC, McSim1993 commented on app/controllers/user/index.js
> +        });
а else? что будет если пароль неправильный. или user в базе не найден, а ты на нем вызовешь метод authenticate?

2017-05-12 09:13 UTC, McSim1993 commented on app/controllers/user/index.js
> +        return("Please log in");
Все ошибки нужно возвращать в установленном нами формате

2017-05-12 09:13 UTC, McSim1993 commented on app/controllers/user/index.js
>                  log.debug("there are your decks:");
будет просто залогирована эта надпись)

2017-05-12 09:13 UTC, McSim1993 commented on app/controllers/user/index.js
>          log.debug('user is not logged in');
опять таки разные ошибки, при обращении незалогированного пользователя. Я бы вообще вынес ручки register и login из контроллера "User". потому что и регистрацию и логин выполняют не юзеры. Юзер - залогиненный пользователь. А проверку session.user_id(кстати нижнее подчеркивание в названии - плохо) можно в контроллере юзер сделать отдельным методом, чтобы она единообразная была

2017-05-13 15:04 UTC, merged